Repository procore-oss/blueprinter, pull requests merged in 2019-05, with the labels that each got.

#154 fix: Early return identifier fields if view matches.
  lib/blueprinter/view_collection.rb
  spec/integrations/shared/base_render_examples.rb
Labels: bug, needs code review, needs testing

#155 v0.17.0 Release
  CHANGELOG.md
  lib/blueprinter/version.rb
Labels: Release

#156 Dont run benchmarks for ruby 2.2
  .circleci/config.yml
Labels: needs code review
